// backend/routes/totp.js
import express from "express";
import { verifyToken } from "../middleware/auth.js";
import { totpSetup, totpEnable, totpDisable } from "../controllers/totpController.js";

const router = express.Router();

/**
 * @swagger
 * tags:
 *   name: TOTP (2FA)
 *   description: Time-based One-Time Password two-factor authentication management
 */

/**
 * @swagger
 * /api/auth/totp/setup:
 *   post:
 *     summary: Initialise TOTP setup — returns a secret and QR code URI
 *     description: >
 *       Generates a new TOTP secret for the user and returns the otpauth URI
 *       and a base64-encoded QR code PNG. The secret is stored encrypted on the
 *       server. Call /enable to activate 2FA after scanning.
 *     tags: [TOTP (2FA)]
 *     security:
 *       - bearerAuth: []
 *     responses:
 *       200:
 *         description: TOTP setup data
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 otpauthUrl:
 *                   type: string
 *                   description: otpauth:// URI to encode in a QR code
 *                   example: "otpauth://totp/Cipher Cloud:alice%40example.com?secret=BASE32SECRET&issuer=Cipher Cloud"
 *                 qrCode:
 *                   type: string
 *                   description: Base64-encoded PNG QR code (data URI)
 *                   example: "data:image/png;base64,iVBORw0K..."
 *       401:
 *         description: Unauthorized
 *       500:
 *         description: Setup failed
 */
router.post("/setup", verifyToken, totpSetup);

/**
 * @swagger
 * /api/auth/totp/enable:
 *   post:
 *     summary: Enable TOTP 2FA by confirming a valid code
 *     description: >
 *       Verifies the provided TOTP code against the pending secret generated by
 *       /setup. If valid, marks the user's account as 2FA-enabled.
 *     tags: [TOTP (2FA)]
 *     security:
 *       - bearerAuth: []
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required: [code]
 *             properties:
 *               code:
 *                 type: string
 *                 description: 6-digit TOTP code from authenticator app
 *                 example: "123456"
 *     responses:
 *       200:
 *         description: TOTP enabled successfully
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 message:
 *                   type: string
 *                   example: TOTP enabled
 *       400:
 *         description: Invalid or expired TOTP code
 *       401:
 *         description: Unauthorized
 */
router.post("/enable", verifyToken, totpEnable);

/**
 * @swagger
 * /api/auth/totp/disable:
 *   post:
 *     summary: Disable TOTP 2FA
 *     description: >
 *       Verifies the current TOTP code then disables 2FA on the account and
 *       removes the stored encrypted secret.
 *     tags: [TOTP (2FA)]
 *     security:
 *       - bearerAuth: []
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required: [code]
 *             properties:
 *               code:
 *                 type: string
 *                 description: 6-digit TOTP code to confirm disable
 *                 example: "654321"
 *     responses:
 *       200:
 *         description: TOTP disabled
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 message:
 *                   type: string
 *                   example: TOTP disabled
 *       400:
 *         description: Invalid TOTP code
 *       401:
 *         description: Unauthorized
 */
router.post("/disable", verifyToken, totpDisable);

export default router;
